services:
  balance:
    build:
      args:
        VITE_GAME_SERVER: ${VITE_GAME_SERVER}
      context: .
      dockerfile: Dockerfile
    container_name: balance
    ports:
      - "2567:2567"
      - "8080:8080"
    restart: unless-stopped
